### ISSUE TITLE
crash on world loading: NoClassDefFoundError

### ISSUE THREAD

**Issue by Biviho** [ikexing-cn/RandomTweaker#31]
the game crash while loading a new world in the latest release (1.1.7) and also previous.
tested in a large modpack environment.

vanilla fix said it involves randomtweaker, TaN and lag goggle
matteroverdrive is not in the pack

edit- forgot the log: [The mighty Log](https://pastebin.com/J3E5BHnz)

**Comment by ikexing-cn** [comment]
This should not be triggered, can you provide the full `latest.log`, I need it to find out what the problem is.

**Comment by ikexing-cn** [comment]
by the way.

> ink.ikx.rt.impl.matteroverdrive.IMatterOverdriveAndroid.isPlayerAndroid(IMatterOverdriveAndroid.java:15)

It's like you are calling is `isPlayerAndroid` of `ZenScript` without **MatterOverive** Mod.

**Comment by Biviho** [comment]
unfortunately it couldn't possible be that, cause i haven't started to use any methods from random tweaker.
This crash happened on the first time i started the game, just after installing the mod

latest.log from today
[latest.log](https://github.com/ikexing-cn/RandomTweaker/files/7027393/latest.log)

it's a big, work in progress modpack, if it can help i can give a copy to you or i can try to figura out if there is some incompatibilty by disableing some mods, but it will take me some time as i'm pretty busy from work also

**Comment by ikexing-cn** [comment]
Can I ask you about your `tan` version, I probably know what the problem is.

**Comment by Biviho** [comment]
ToughAsNails-1.12.2-3.1.0.141-universal

the latest beta release for 1.12
