### ISSUE TITLE
植物魔法给凝矿兰添加矿物转换报错

### ISSUE THREAD

**Issue by Anidlebrain** [ikexing-cn/RandomTweaker#35]
我在对凝矿兰魔改的时候报错 “This ore was empty!” ，我看了源码如下，判断十分的简单明了，但我可以确定一件事情这个矿物的矿词是存在的，并且我使用原先植物魔法的魔改可以生效。我不清楚是我魔改写的问题，还是哪里的bug。
`        
if (ore.isEmpty()) {
    CraftTweakerAPI.logError("This ore was empty!");
    return;
}
`
使用Modtweaker的魔改代码：https://github.com/Anidlebrain/magic_higanbana/blob/master/magic_higanbana/overrides/scripts/CraftTweaker/mods/botania/Orechid.zs
使用RandomTweaker的魔改代码：https://github.com/Anidlebrain/magic_higanbana/blob/master/magic_higanbana/overrides/scripts/CraftTweaker/mods/randomtweaker/botania/Orechid.zs
两个魔改代码同时运行时的crt的log：https://paste.ubuntu.com/p/5nHpR6pKYM/

**Comment by XHL315** [comment]
配置文件开启了凝矿兰的功能吗？

**Comment by ikexing-cn** [comment]
> [INITIALIZATION][CLIENT][INFO] 1
[INITIALIZATION][CLIENT][INFO] 2
[INITIALIZATION][CLIENT][INFO] 3
[INITIALIZATION][CLIENT][INFO] 4
[INITIALIZATION][CLIENT][INFO] 5
[INITIALIZATION][CLIENT][INFO] 6
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 7
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 8
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 9
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 10
[INITIALIZATION][CLIENT][ERROR] This ore was empty!

既然1-5能跑，那么我猜测后面的矿词是你crt自己加的。
所以你要确保添加矿词的脚本优先级比你现在脚本的优先级高。

**Comment by Anidlebrain** [comment]
配置文件已经开启凝矿兰的功能，并且这个矿词不是我添加的，是[TAIGA]匠魂合金附加 (Tinkers Alloying Addon) mod 的一个矿物

**Comment by ikexing-cn** [comment]
> 并且我使用原先植物魔法的魔改可以生效。我不清楚是我魔改写的问题，还是哪里的bug。

MT的确实可以正常输出不会报错。
至于生效原因，配置文件中有一条内容：

> If true, the Orechid will keep the Botania recipes. [Valid only for modified results | default: true]
默认为真，则不会删除植物魔法自带的配方，并且你使用了MT调用了API增删了配方，也是属于植物魔法本身配方的内容。
可能符合目前情况。

---

> [INITIALIZATION][CLIENT][INFO] 1
[INITIALIZATION][CLIENT][INFO] 2
[INITIALIZATION][CLIENT][INFO] 3
[INITIALIZATION][CLIENT][INFO] 4
[INITIALIZATION][CLIENT][INFO] 5
[INITIALIZATION][CLIENT][INFO] 6
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 7
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 8
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 9
[INITIALIZATION][CLIENT][ERROR] This ore was empty!
[INITIALIZATION][CLIENT][INFO] 10
[INITIALIZATION][CLIENT][ERROR] This ore was empty!

> 但我可以确定一件事情这个矿物的矿词是存在的
如果1-5能正常执行，那么十有八九和RT自身无关……确保矿辞内真正的含有`IItemStack`

**Comment by ikexing-cn** [comment]
嗯我刚失误了，1-5是delore，不过CrT给出的`ore.isEmpty()`的具体实现是`OreDictionary.getOres(getName()).isEmpty()`，所以应该不是RT的问题。

**Comment by Anidlebrain** [comment]
> 确保矿辞内真正的含有IItemStack

谢谢，经过我的测试，我已经找到问题了，确实是OreDictionary里面没有IItemStack，我用crt在加了一次矿词就可以了。虽然我不知道为什么/ct hand会显示矿词，但问题已经解决。
