### ISSUE TITLE
Crash while Initializing game

### ISSUE THREAD

**Issue by Dieinbed** [ikexing-cn/RandomTweaker#39]
crash report:

[https://paste.ubuntu.com/p/4Ns9QsCgFw/](url)

**Comment by ikexing-cn** [comment]
How did it happen?

**Comment by Dieinbed** [comment]
log:
https://paste.ubuntu.com/p/yMNZSVH4SS/

**Comment by XHL315** [comment]
可以给我你的 mods 列表吗，我复现不了你的问题

**Comment by Dieinbed** [comment]
https://drive.google.com/file/d/17i58MdPN_kKj59NAlyt3KWi9Jbdu4dfH/view?usp=sharing

**Comment by XHL315** [comment]
先加上 CoT，此 BUG 将在下个版本修复
