### ISSUE TITLE
凝矿兰魔改 getOreWeight 接口 空指针异常

### ISSUE THREAD

**Issue by Anidlebrain** [ikexing-cn/RandomTweaker#40]
魔改代码：[凝矿兰魔改](https://github.com/Anidlebrain/magic_higanbana/blob/master/magic_higanbana/overrides/scripts/CraftTweaker/mods/randomtweaker/botania/Orechid.zs)
魔改日志：[crafttweaker.log](https://github.com/ikexing-cn/RandomTweaker/files/7175195/crafttweaker.log)

**Comment by ikexing-cn** [comment]
我🌂兵了，写了个无卵用的filter条件然后把逻辑搞炸了...下一个版本会修复这个问题
