### ISSUE TITLE
魔力池事件导致魔力池没有输出

### ISSUE THREAD

**Issue by Anidlebrain** [ikexing-cn/RandomTweaker#41]
使用版本：1.1.17
魔力池事件：[魔改代码](https://github.com/Anidlebrain/magic_higanbana/blob/master/magic_higanbana/overrides/scripts/CraftTweaker/mods/randomtweaker/botania/PoolTradeEvent.zs)
魔力池：[魔改代码](https://github.com/Anidlebrain/magic_higanbana/blob/master/magic_higanbana/overrides/scripts/CraftTweaker/mods/botania/ManaInfusion.zs)
魔力池事件第三十行代码 `event.setOutput(event.output);` 不管写不写都没有输出。
由于有日志打印，我可以确认第14行被执行到了。
测试例子：
1.丢入我魔改后的物品到魔力池，没有物品输出。
2.丢入曲奇饼到魔力池，这是植物魔法原始的配方，但在魔力池里不会变成魔力曲奇。

**Comment by ikexing-cn** [comment]
是否`event.cancel`执行了，这个方法执行了会阻止全部输出。

**Comment by Anidlebrain** [comment]
应该不会，因为已经执行了第14行，后面的if语句是false，就直接到第30行了。

**Comment by ikexing-cn** [comment]
稍后我将查实此问题。

**Comment by ikexing-cn** [comment]
``` zenscript
if(!world.remote)
{
    event.cancel();
}
```
经过确认是这个的问题，看起来魔力池需要双端返回，所以请不要执行这个。

**Comment by Anidlebrain** [comment]
> 所以请不要执行这个。

好的，我写这个主要是看[wiki](https://github.com/ikexing-cn/RandomTweaker/blob/1.12/wiki/zh_cn/modSupport/Event/PoolTradeEvent.md)上写了这个，还以为必须要写。

**Comment by ikexing-cn** [comment]
> > 所以请不要执行这个。
> 
> 好的，我写这个主要是看[wiki](https://github.com/ikexing-cn/RandomTweaker/blob/1.12/wiki/zh_cn/modSupport/Event/PoolTradeEvent.md)上写了这个，还以为必须要写。

这就去修改wiki的提示。。
