### ISSUE TITLE
凝矿兰魔改优化

### ISSUE THREAD

**Issue by Anidlebrain** [ikexing-cn/RandomTweaker#42]
使用版本：1.1.17
凝矿兰：[魔改代码](https://github.com/Anidlebrain/magic_higanbana/blob/master/magic_higanbana/overrides/scripts/CraftTweaker/mods/randomtweaker/botania/Orechid.zs)
getOreWeight 接口会返回空的对象，第23行代码 `if (!isNull(ore))`  第25行代码 ` if (!ore.empty)`  如果不写会导致下面 add的时候报错 `This ore was empty!` 错误原因 和 #35 一样
希望 getOreWeight 不会返回 空的对象

**Comment by ikexing-cn** [comment]
想不到更好的处理方式，另矿词因为crt的特性是不会存在空对象的，所以理论上判断`ore.empty`足以

**Comment by Anidlebrain** [comment]
> 理论上判断ore.empty足以

确实，我测试了一下，只需要判断 这个就可以了，并且下面输出的矿词是我整合包里不存在的矿词。

**Comment by ikexing-cn** [comment]
> 并且下面输出的矿词是我整合包里不存在的矿词。

毕竟矿辞只是为了区分同类物品的标识，所以植魔原版提前写好判断是很正常的事情。

**Comment by ikexing-cn** [comment]
下一次更新中将不会再输出空的矿辞了

**Comment by Anidlebrain** [comment]
thanks
