### ISSUE TITLE
Aspect添加材质加载问题

### ISSUE THREAD

**Issue by Anidlebrain** [ikexing-cn/RandomTweaker#44]
[步骤]
我创建了一个 stat 的Aspect
`
var stat as Aspect = VanillaFactory.createAspect("stat", 0x4169E1);
stat.register();
`
在材质\resources\contenttweaker\textures\aspects 放了一个stat.png 但没有成功加载材质
而后我把.png去了，即stat.png改为stat，游戏中正常显示了材质。

[期望] 
可以正确的加载stat.png文件而不是stat

**Comment by ikexing-cn** [comment]
确实属于bug，不过这一部分是@XHL315 负责，所以可能修复不会那么及时。

**Comment by XHL315** [comment]
sorry，这属于我的疏忽的问题，下个版本将修复这个 BUG
