### ISSUE TITLE
星辉魔法更多的支持

### ISSUE THREAD

**Issue by Anidlebrain** [ikexing-cn/RandomTweaker#46]
1. 晶金座在效应放大器上的矿物转换魔改，支持不限于石头的矿物转换，JEI显示。
2. [星辉转化](https://docs.blamejared.com/1.12/en/Mods/Astral_Sorcery/Transmutation/) 支持 指定星座的 [聚能水晶](https://www.mcmod.cn/item/62447.html?jump=110726) 魔改

**Comment by Anidlebrain** [comment]
[共鸣祭坛](https://www.mcmod.cn/item/118581.html) 能否添加事件？

**Comment by ikexing-cn** [comment]
> [共鸣祭坛](https://www.mcmod.cn/item/118581.html) 能否添加事件？

这个不行，之前尝试过研究星辉那一套的recipe系统，没研究明白

**Comment by ikexing-cn** [comment]
技术原因，无法实现

**Comment by Water-Moon** [comment]
Implemented. #54
